### PR TITLE
ci: create format, build and cargo test github actions

### PR DESCRIPTION
**Pull request by liyang8246**
Actually, it’s an update to GitHub Action

look like it:
d632908f-2ff5-46c9-b2a7-673776256ab7

### CODE REVIEW

**Review by Placebo27 — CHANGES_REQUESTED** [review]
LGTM! In this pr, GitHub Actions' behavior conforms to the definition of this script.
But please abide by [conventional commits](https://www.conventionalcommits.org/zh-hans/v1.0.0/) to modify this pr, thx.
You can change `github: ` to `ci: `.
It is also possible to rewrite the commit in more detail, for example, using `ci: create format, build and cargo test github actions`.

**Comment by liyang8246** [comment]
> LGTM! In this pr, GitHub Actions' behavior conforms to the definition of this script. But please abide by [conventional commits](https://www.conventionalcommits.org/zh-hans/v1.0.0/) to modify this pr, thx. You can change `github: ` to `ci: `. It is also possible to rewrite the commit in more detail, for example, using `ci: create format, build and cargo test github actions`.

Thank you for the guidance! I’ve updated the PR to adhere to conventional commits by changing github: to ci: and have detailed the commit message as suggested.

**Comment by Placebo27** [comment]
You may forget to amend the title, it's very important.

**Comment by liyang8246** [comment]
> You may forget to amend the title, it's very important.

😭

**Review by Placebo27 — APPROVED** [review]
Nice job.

**Review by luojia65 — APPROVED** [review]
LGTM

**Pull request merged**
